title: "DNA Study Notes"
description: "Comprehensive notes and resources for understanding DNA."
baseurl: "/dna-study"  # Required for GitHub Pages
url: "https://daveremy.github.io"  # GitHub Pages URL
theme: minima

# Plugins
plugins:
  - jekyll-feed
